// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using ImageKit;
using System.IO;
using System.Data;
using MySql.Data.MySqlClient;

namespace DentalSV
{
	public partial class AddPhotoViewController : NSViewController
	{
		public AddPhotoViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            if (ValuesForCreateReception.ChoosenPatientEntire != null)
            {
                //Значения полей для пациента который выбран
                IDTxtField.StringValue = ValuesForCreateReception.ChoosenPatientEntire.Id.ToString();
                FIOTxtField.StringValue = ValuesForCreateReception.ChoosenPatientEntire.FIO.ToString();
                BirthDateTxtField.StringValue = ValuesForCreateReception.ChoosenPatientEntire.BirthDate.ToString();
                PhoneTxtField.StringValue = ValuesForCreateReception.ChoosenPatientEntire.Phone.ToString();
                DatePicker.DateValue = (NSDate)DateTime.Now;
                ChoosenPatientIndicator.StringValue = "Пациент выбран";
                ChoosenPatientIndicator.TextColor = NSColor.SystemGreen;
                ValuesForCreateReception.ChoosenPatientEntire = null;
            }
            else
            {
                StarIndicator.Hidden = true;
                TxtFieldForPathOutlet.Hidden = false;
                DatePicker.DateValue = (NSDate)DateTime.Now;
            }
        }

        partial void BtnBack(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene2", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene2Main") as NSWindowController;
            window.ShowWindow(this);
        }

        partial void TxtFieldForPathAction(NSObject sender)
        {
            if (TxtFieldForPathOutlet.StringValue == "")
            {

            }
            else
            {
                byte[] imageBytes = File.ReadAllBytes(TxtFieldForPathOutlet.StringValue);
                MemoryStream memoryStream = new MemoryStream(imageBytes);
                NSImage image = new NSImage(NSData.FromStream(memoryStream));
                ImgView.Image = image;
                TxtFieldForPathOutlet.Hidden = true;
            }
        }


        public string CheckForPatient()
        {
            DB db = new DB();

            DataTable table = new DataTable();

            MySqlDataAdapter adapter = new MySqlDataAdapter();

            MySqlCommand command = new MySqlCommand("SELECT Patient_id FROM Patients WHERE Name=@name AND Surname=@surname AND Patronymic=@patronymic;", db.GetConnection());

            string[] Parametrs = new string[3];
            int counter = 0;
            for (int i = 0; i < FIOTxtField.StringValue.Length; i++)
            {
                if (FIOTxtField.StringValue[i].ToString() != " ")
                {
                    Parametrs[counter] += FIOTxtField.StringValue[i];
                }
                else
                    counter++;
            }

            command.Parameters.Add("@name", MySqlDbType.String).Value = Parametrs[1];
            command.Parameters.Add("@surname", MySqlDbType.String).Value = Parametrs[0];
            command.Parameters.Add("@patronymic", MySqlDbType.String).Value = Parametrs[2];

            adapter.SelectCommand = command;

            adapter.Fill(table);

            if (table.Rows.Count < 1)
            {
                var alert = new NSAlert()
                {
                    AlertStyle = NSAlertStyle.Informational,
                    InformativeText = $"Возможна ошибка при занесении пациента. Проверьте правильность заполнения поля ФИО в порядке: Фамилия, Имя, Отчество.",
                    MessageText = $"Пациент не найден",
                };
                alert.AddButton("Ок");
                alert.BeginSheetForResponse(this.View.Window, (result) => {
                    // Should we delete the requested row?
                    if (result == 1001)
                    {
                    }
                });
                return "Не найден";
            }
            if (table.Rows.Count == 1)
            {
                return table.Rows[0].ItemArray[0].ToString();
            }
            if (table.Rows.Count > 1)
            {
                var alert = new NSAlert()
                {
                    AlertStyle = NSAlertStyle.Informational,
                    InformativeText = $"При поиске пциента были найдены два или более человека подходящие под поисанные параметры.",
                    MessageText = $"Найдено несколько пациентов",
                };
                alert.AddButton("Ок");
                alert.BeginSheetForResponse(this.View.Window, (result) => {
                    // Should we delete the requested row?
                    if (result == 1001)
                    {
                    }
                });
                return "Найдено несколько";
            }
            return "Ошибка поиска";
        }

        partial void FIOTxtFieldAction (NSObject sender)
        {
            if (CheckForPatient() != "Не найден" && CheckForPatient() != "Найдено несколько" && CheckForPatient() != "Ошибка поиска")
            {
                StarIndicator.Hidden = false;
                ChoosenPatientIndicator.StringValue = "Пациент выбран";
                ChoosenPatientIndicator.TextColor = NSColor.SystemGreen;

                DB db = new DB();

                DataTable table = new DataTable();

                MySqlDataAdapter adapter = new MySqlDataAdapter();

                MySqlCommand command = new MySqlCommand("Select Patient_id, BirthDate, Phone From Patients Where Patient_id = @id;", db.GetConnection());
                command.Parameters.Add("@id", MySqlDbType.Int32).Value = CheckForPatient();
                adapter.SelectCommand = command;
                adapter.Fill(table);

                NSTextField[] TxtFields = { IDTxtField, BirthDateTxtField, PhoneTxtField };

                foreach (DataRow row in table.Rows)
                {
                    var cells = row.ItemArray;
                    int counter = 0;
                    foreach (object cell in cells)
                    {
                        if (cell == DBNull.Value)
                        {
                            TxtFields[counter].StringValue = "";
                        }
                        else
                        {
                            switch (counter)
                            {
                                case 0:
                                    IDTxtField.StringValue = cell.ToString();
                                    break;
                                case 1:
                                    DateTime datetime = (DateTime)cell;
                                    BirthDateTxtField.StringValue = datetime.ToString("dd/MM/yyyy");
                                    break;
                                case 2:
                                    PhoneTxtField.StringValue = cell.ToString();
                                    break;
                            }
                        }
                        counter++;
                    }
                }
                BtnSavePhotoOutlet.Enabled = true;
            }
            else
            {
                BtnSavePhotoOutlet.Enabled = false;
                StarIndicator.Hidden = true;
                ChoosenPatientIndicator.StringValue = "Пациент не выбран";
                ChoosenPatientIndicator.TextColor = NSColor.SystemGray;

                NSTextField[] TxtFields = { IDTxtField, BirthDateTxtField, PhoneTxtField };

                for (int i = 0; i < TxtFields.Length; i++)
                {
                    TxtFields[i].StringValue = "";
                }
            }
        }

        partial void BtnChoosePat(NSObject sender)
        {
            PublicValues.ChoosePatForPhoto = true;
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene6", null);
            var window = storyboard.InstantiateControllerWithIdentifier("ChoosePatient432") as NSWindowController;
            window.ShowWindow(this);
        }

        partial void BtnSavePhotoAction(NSObject sender)
        {
            DB db = new DB();

            DataTable table = new DataTable();

            MySqlDataAdapter adapter = new MySqlDataAdapter();

            MySqlCommand command = new MySqlCommand("INSERT INTO PatientsPhoto (Patient_id, Date, Photo) VALUES (@pat_id, @datetime, @photo);", db.GetConnection());

            command.Parameters.Add("@pat_id", MySqlDbType.Int32).Value = IDTxtField.StringValue;
            command.Parameters.Add("@datetime", MySqlDbType.DateTime).Value = (DateTime)DatePicker.DateValue;

            byte[] imageBytes = File.ReadAllBytes(TxtFieldForPathOutlet.StringValue);

            command.Parameters.Add("@photo", MySqlDbType.LongBlob).Value = imageBytes;

            db.OpenConnection();
            command.ExecuteNonQuery();
            db.CloseConnection();

            var alert = new NSAlert()
            {
                AlertStyle = NSAlertStyle.Informational,
                InformativeText = $"Фотография была прикреплена к выбранному пациенту.",
                MessageText = $"Фотография добавлена",
            };
            alert.AddButton("Ок");
            alert.BeginSheetForResponse(this.View.Window, (result) => {
                // Should we delete the requested row?
                if (result == 1001)
                {
                }
                View.Window.OrderOut(Self);
                var storyboard = NSStoryboard.FromName("Scene8", null);
                var window = storyboard.InstantiateInitialController() as NSWindowController;
                window.ShowWindow(this);
            });
            
        }
    }
}
