// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MySql.Data.MySqlClient;
using System.Data;
using CoreGraphics;
using System.IO;

namespace DentalSV
{
	public partial class AllPhotosViewController : NSViewController
	{
		public AllPhotosViewController (IntPtr handle) : base (handle)
		{
		}
        public override void ViewDidLoad()
        {
            GenerateImages();
        }
        private void GenerateImages()
        {
            DB db = new DB();

            DataTable table = new DataTable();

            MySqlDataAdapter adapter = new MySqlDataAdapter();

            MySqlCommand command = new MySqlCommand("select Photo, Date, PatientPhoto_id from PatientsPhoto where Patient_id=@id;", db.GetConnection());
            command.Parameters.Add("@id", MySqlDbType.Int32).Value = PublicValues.ChoosenPatientID;

            adapter.SelectCommand = command;

            adapter.Fill(table);

            int counter = 0;
            nfloat width = 275;
            nfloat height = 220;
            nfloat x = 20;
            nfloat y = 160;

            for (int i = 0; i < table.Rows.Count; i++)
            {
                NSImageView imageView = new NSImageView(new CGRect(x, y, width, height));

                byte[] imageBytes = (byte[])table.Rows[i].ItemArray[0];
                MemoryStream memoryStream = new MemoryStream(imageBytes);
                NSImage image = new NSImage(NSData.FromStream(memoryStream));
                imageView.Image = image;

                imageView.ImageScaling = NSImageScale.ProportionallyUpOrDown;
                this.View.AddSubview(imageView);

                counter++;
                if (counter != 3)
                {
                    x += 313;
                }
                else
                {
                    x = 20;
                    y -= 249;
                    counter = 0;
                }
            }
        }
        partial void BtnBack(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene3", null);
            var window = storyboard.InstantiateControllerWithIdentifier("MedicalCard") as NSWindowController;
            window.ShowWindow(this);
        }
    }
}
