// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Threading;

namespace DentalSV
{
	public partial class LoginFailViewController : NSViewController
	{
		public LoginFailViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override NSObject RepresentedObject
        {
            get
            {
                return base.RepresentedObject;
            }
            set
            {
                base.RepresentedObject = value;
                // Update the view, if already loaded.
            }
        }

        partial void BtnBack(NSObject sender)
        {
            NSViewController AuthController = Storyboard.InstantiateControllerWithIdentifier("AuthController") as NSViewController;
            View.Window.ContentViewController = AuthController;
        }
    }
}
