// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MySql.Data.MySqlClient;
using System.Data;
using System.IO;

namespace DentalSV
{
	public partial class MenuViewController : NSViewController
	{
		public MenuViewController (IntPtr handle) : base (handle)
		{
		}
        partial void PatientBtn(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene3", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene3Main") as NSWindowController;
            window.ShowWindow(this);
        }
        partial void ReceptionBtn(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene2", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene2Main") as NSWindowController;
            window.ShowWindow(this);
        }
        partial void AddPhotos(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene8", null);
            var window = storyboard.InstantiateInitialController() as NSWindowController;
            window.ShowWindow(this);
        }
        partial void CreateReceptionBtn(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene6", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene6Main") as NSWindowController;
            window.ShowWindow(this);
        }
        partial void CreatePatientBtn(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene4", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene4Main") as NSWindowController;
            window.ShowWindow(this);
        }
        partial void BtnLogHis(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene9", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene9Main") as NSWindowController;
            window.ShowWindow(this);
        }
        partial void BtnProtez(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene10", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene10Main") as NSWindowController;
            window.ShowWindow(this);
        }
    }
}
