// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MySql.Data.MySqlClient;
using System.Data;

namespace DentalSV
{
	public partial class OldCardsViewController : NSViewController
	{
		public OldCardsViewController (IntPtr handle) : base (handle)
		{
            PublicValues.handle = (handle);
        }
        public override void ViewDidLoad()
        {
            UpdateTxtFieldsForNewCard();
            UpdateEarlyCardsTableView();
        }

        public void UpdateTxtFieldsForNewCard()
        {
            DB db = new DB();

            DataTable table = new DataTable();

            MySqlDataAdapter adapter = new MySqlDataAdapter();

            MySqlCommand command = new MySqlCommand("select ChronicDiseases,Injurys, Allergies, InfectiousDiseases, MucosalCondition, VisualInspection, ProstheticPlan from MedicalCard where MedCard_id=@id;", db.GetConnection());
            command.Parameters.Add("@id", MySqlDbType.Int32).Value = PublicValues.ChoosenEarlyMedCard_id;
            adapter.SelectCommand = command;

            adapter.Fill(table);

            NSTextField[] TxtFields = {TxtFieldChronicalDiseases, TxtFieldInjurys, TxtFieldAllergies, TxtFieldInfectionDiseases,TxtFieldMucosalCondition,TxtFieldVisualInspection,TxtFieldProtethisPlan };

            foreach (DataRow row in table.Rows)
            {
                var cells = row.ItemArray;
                int counter = 0;
                foreach (object cell in cells)
                {
                    if (cell == DBNull.Value)
                    {
                        TxtFields[counter].StringValue = "";
                    }
                    else
                    {
                        TxtFields[counter].StringValue = (string)cell;
                    }
                    counter++;
                }
            }

            if (PublicValues.ChoosenEarlyMedCard_id != 0)
            {
                command = new MySqlCommand("Select CreationDateTime From MedicalCard Where MedCard_id=@id;", db.GetConnection());
                command.Parameters.Add("@id", MySqlDbType.Int32).Value = PublicValues.ChoosenEarlyMedCard_id;
                adapter.SelectCommand = command;
                table = new DataTable();
                adapter.Fill(table);
                LableDateUpdate.StringValue = "Дата обновления карты - " + table.Rows[0].ItemArray[0].ToString();
            }
        }

        private EarlyMedCardsTableDataSource DataSource = new EarlyMedCardsTableDataSource();
        public void UpdateEarlyCardsTableView()
        {
            DB db = new DB();

            DataTable table = new DataTable();

            MySqlDataAdapter adapter = new MySqlDataAdapter();

            MySqlCommand command = new MySqlCommand("Select CreationDateTime, MedCard_id From MedicalCard Where Patient_id=@id;", db.GetConnection());
            command.Parameters.Add("@id", MySqlDbType.Int32).Value = PublicValues.ChoosenPatientID;

            adapter.SelectCommand = command;

            adapter.Fill(table);

            DataSource = new EarlyMedCardsTableDataSource();

            foreach (DataRow row in table.Rows)
            {
                int counter = 1;
                var datetime = "";
                var medCard_id = 0;

                var cells = row.ItemArray;
                foreach (object cell in cells)
                {
                    switch (counter)
                    {
                        case 1:
                            datetime = cell.ToString();
                            break;
                        case 2:
                            medCard_id = (int)cell;
                            break;
                    }
                    counter++;
                }
                DataSource.EarlyMedCardsS.Add(new EarlyMedCards(datetime, medCard_id));
                // Populate the Product Table
                OldCardsTableView.DataSource = DataSource;
                OldCardsTableView.Delegate = new EarlyMedCardsTableDelegate(this, DataSource);
            }
        }

        partial void BtnDelntalFormula(NSObject sender)
        {
            PublicValues.DFormulaOldCardOpened = true;
            var storyboard = NSStoryboard.FromName("Scene4", null);
            var window = storyboard.InstantiateControllerWithIdentifier("DentalFormula") as NSWindowController;
            window.ShowWindow(this);
        }

        partial void BtnBack(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene3", null);
            var window = storyboard.InstantiateControllerWithIdentifier("MedicalCard") as NSWindowController;
            window.ShowWindow(this);
        }
    }
}
