// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MySql.Data.MySqlClient;
using System.Data;

namespace DentalSV
{
	public partial class PatProtzesViewController : NSViewController
	{
		public PatProtzesViewController (IntPtr handle) : base (handle)
		{
		}
        private PatRotezesTableDataSourse DataSource = new PatRotezesTableDataSourse();
        public override void ViewDidLoad()
        {
            UpdateTableView();
        }
        private void UpdateTableView()
        {
            DataSource = new PatRotezesTableDataSourse();

            DB db = new DB();

            DataTable table = new DataTable();

            MySqlDataAdapter adapter = new MySqlDataAdapter();

            MySqlCommand command = new MySqlCommand("select RemovableProsthesis_id, Materials.Name, FullPartial.Title, DentalSet.Title, Clamers.Title, Saddles.Quantity, ClamersQuntity from RemovableProsthesis inner join Materials on RemovableProsthesis.Material_id=Materials.Material_id inner join FullPartial on RemovableProsthesis.FullPartial_id = FullPartial.FullPartial_id inner join DentalSet on RemovableProsthesis.DentalSet_id = DentalSet.DentalSet_id inner join Clamers on RemovableProsthesis.Clamer_id = Clamers.Clamer_id inner join Saddles on RemovableProsthesis.Saddle_id = Saddles.Saddle_id where Patient_id = @id order by RemovableProsthesis_id desc;", db.GetConnection());

            command.Parameters.Add("@id", MySqlDbType.Int32).Value = PublicValues.ChoosenPatientID;

            adapter.SelectCommand = command;

            adapter.Fill(table);

            foreach (DataRow row in table.Rows)
            {
                int counter = 1;
                int protez_id = new int();
                var material = "";
                var size = "";
                var dentalset = "";
                var clammers = "";
                int saddles = new int();
                int clammersquantity = new int();

                var cells = row.ItemArray;
                foreach (object cell in cells)
                {
                    switch (counter)
                    {
                        case 1:
                            protez_id = (int)cell;
                            break;
                        case 2:
                            material = (string)cell;
                            break;
                        case 3:
                            size = (string)cell;
                            break;
                        case 4:
                            dentalset = (string)cell;
                            break;
                        case 5:
                            clammers = (string)cell;
                            break;
                        case 6:
                            saddles = (int)cell;
                            break;
                        case 7:
                            clammersquantity = (int)cell;
                            break;
                    }
                    counter++;
                }
                DataSource.ProtezesS.Add(new Protezes(protez_id, material, size, dentalset, clammers, saddles, clammersquantity));
                ProtezisTableView.DataSource = DataSource;
                ProtezisTableView.Delegate = new PatRotezesTableDelegate(DataSource);
            }
            //Чистит таблицу при отсутсвии записей
            if (table.Rows.Count == 0)
            {
                DataSource.ProtezesS.Clear();
                ProtezisTableView.DataSource = DataSource;
                ProtezisTableView.Delegate = new PatRotezesTableDelegate(DataSource);
            }
        }
        partial void BtnBack(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene3", null);
            var window = storyboard.InstantiateControllerWithIdentifier("MedicalCard") as NSWindowController;
            window.ShowWindow(this);
        }
        partial void AddProtez(NSObject sender)
        {
            View.Window.OrderOut(Self);
            var storyboard = NSStoryboard.FromName("Scene10", null);
            var window = storyboard.InstantiateControllerWithIdentifier("Scene10Main") as NSWindowController;
            window.ShowWindow(this);
        }
    }
}
